### ISSUE TITLE
異常系のテストコードの作成

### ISSUE THREAD

**Issue by hasyrails** [hasyrails/sample_app_for_rspec_issue_making#21]
- [ ] #13 ```presence: true```のバリデーション検証テスト

- [ ] #14 ```uniqueness: true```のバリデーション検証テスト

- [ ] #15  ログインに必要なパラメータの検証テスト

- [ ] #16 ```required_login```メソッドの検証テスト

- [ ] #17 ```verify_access```メソッドの検証テスト
